/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooleanResponse
 */
export interface BooleanResponse {
    /**
     * 
     * @type {string}
     * @memberof BooleanResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BooleanResponse
     */
    errorCode?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BooleanResponse
     */
    result?: boolean;
}

/**
 * Check if a given object implements the BooleanResponse interface.
 */
export function instanceOfBooleanResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BooleanResponseFromJSON(json: any): BooleanResponse {
    return BooleanResponseFromJSONTyped(json, false);
}

export function BooleanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function BooleanResponseToJSON(value?: BooleanResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': value.errorMessage,
        'errorCode': value.errorCode,
        'result': value.result,
    };
}

