/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPharmaciesToVisitRequest
 */
export interface GetPharmaciesToVisitRequest {
    /**
     * 
     * @type {number}
     * @memberof GetPharmaciesToVisitRequest
     */
    x?: number;
}

/**
 * Check if a given object implements the GetPharmaciesToVisitRequest interface.
 */
export function instanceOfGetPharmaciesToVisitRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPharmaciesToVisitRequestFromJSON(json: any): GetPharmaciesToVisitRequest {
    return GetPharmaciesToVisitRequestFromJSONTyped(json, false);
}

export function GetPharmaciesToVisitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPharmaciesToVisitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': !exists(json, 'x') ? undefined : json['x'],
    };
}

export function GetPharmaciesToVisitRequestToJSON(value?: GetPharmaciesToVisitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
    };
}

