/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetPharmaciesToVisitResponse } from './GetPharmaciesToVisitResponse';
import {
    GetPharmaciesToVisitResponseFromJSON,
    GetPharmaciesToVisitResponseFromJSONTyped,
    GetPharmaciesToVisitResponseToJSON,
} from './GetPharmaciesToVisitResponse';

/**
 * 
 * @export
 * @interface GetPharmaciesToVisitResponseResponse
 */
export interface GetPharmaciesToVisitResponseResponse {
    /**
     * 
     * @type {string}
     * @memberof GetPharmaciesToVisitResponseResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetPharmaciesToVisitResponseResponse
     */
    errorCode?: number;
    /**
     * 
     * @type {GetPharmaciesToVisitResponse}
     * @memberof GetPharmaciesToVisitResponseResponse
     */
    result?: GetPharmaciesToVisitResponse;
}

/**
 * Check if a given object implements the GetPharmaciesToVisitResponseResponse interface.
 */
export function instanceOfGetPharmaciesToVisitResponseResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPharmaciesToVisitResponseResponseFromJSON(json: any): GetPharmaciesToVisitResponseResponse {
    return GetPharmaciesToVisitResponseResponseFromJSONTyped(json, false);
}

export function GetPharmaciesToVisitResponseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPharmaciesToVisitResponseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'result': !exists(json, 'result') ? undefined : GetPharmaciesToVisitResponseFromJSON(json['result']),
    };
}

export function GetPharmaciesToVisitResponseResponseToJSON(value?: GetPharmaciesToVisitResponseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': value.errorMessage,
        'errorCode': value.errorCode,
        'result': GetPharmaciesToVisitResponseToJSON(value.result),
    };
}

